#!/bin/bash

# Second Brain Setup Script
echo "🧠 Setting up your AI-powered Second Brain..."

# Create directory structure
mkdir -p ~/.second-brain/{knowledge,projects,progress,templates,scripts}
mkdir -p ~/.second-brain/knowledge/{permanent,fleeting,projects,daily,weekly,monthly}
mkdir -p ~/.second-brain/progress/{tasks,subtasks,insights,learnings}

# Create configuration
cat > ~/.second-brain/config.json << 'EOF'
{
  "brain": {
    "name": "J's Second Brain",
    "version": "1.0.0",
    "created": "$(date -Iseconds)",
    "integrations": {
      "claude": true,
      "taskmaster": true,
      "git": true
    }
  },
  "paths": {
    "knowledge": "~/.second-brain/knowledge",
    "projects": "~/.second-brain/projects", 
    "progress": "~/.second-brain/progress",
    "templates": "~/.second-brain/templates"
  },
  "settings": {
    "auto_backup": true,
    "sync_with_git": true,
    "claude_integration": true,
    "daily_review": true
  }
}
EOF

# Create brain CLI tool
cat > ~/.second-brain/scripts/brain << 'EOF'
#!/bin/bash

BRAIN_DIR="$HOME/.second-brain"
DATE=$(date '+%Y-%m-%d')
TIME=$(date '+%H:%M:%S')
DATETIME=$(date -Iseconds)

case "$1" in
    "log")
        # Quick progress log
        echo "[$DATETIME] $2" >> "$BRAIN_DIR/progress/daily-$DATE.md"
        echo "✅ Logged: $2"
        ;;
    "task")
        # Log task progress with Claude analysis
        task_id="$2"
        progress="$3"
        
        # Get task details from taskmaster
        if command -v task-master &> /dev/null; then
            task_details=$(task-master show $task_id 2>/dev/null || echo "Task details not found")
        else
            task_details="Task ID: $task_id"
        fi
        
        # Create progress entry
        cat > "$BRAIN_DIR/progress/tasks/task-$task_id-$DATE.md" << EOL
# Task Progress: $task_id

**Date:** $DATE $TIME
**Task ID:** $task_id
**Progress:** $progress

## Task Details
$task_details

## Progress Log
$progress

## Next Steps
- [ ] To be determined

## Insights
- 

## Related Notes
- 

---
*Auto-generated by Second Brain CLI*
EOL
        
        echo "✅ Task progress logged for $task_id"
        ;;
    "insight")
        # Capture insights and learnings
        insight="$2"
        project="${3:-general}"
        
        cat >> "$BRAIN_DIR/knowledge/permanent/insights-$project.md" << EOL

## $DATE - Insight
$insight

---
EOL
        echo "✅ Insight captured for project: $project"
        ;;
    "review")
        # Daily review with Claude
        echo "🧠 Generating daily review..."
        
        # Collect today's progress
        progress_file="$BRAIN_DIR/progress/daily-$DATE.md"
        if [[ -f "$progress_file" ]]; then
            echo "## Today's Progress" > "/tmp/review-$DATE.md"
            cat "$progress_file" >> "/tmp/review-$DATE.md"
            
            # Use Claude to analyze and create insights
            if command -v claude-code &> /dev/null; then
                echo -e "\n## AI Analysis\n" >> "/tmp/review-$DATE.md"
                claude-code "Analyze this daily progress and provide insights, patterns, and recommendations for tomorrow:" < "$progress_file" >> "/tmp/review-$DATE.md"
            fi
            
            # Move to knowledge base
            mv "/tmp/review-$DATE.md" "$BRAIN_DIR/knowledge/daily/review-$DATE.md"
            echo "✅ Daily review generated: $BRAIN_DIR/knowledge/daily/review-$DATE.md"
        else
            echo "❌ No progress logged today"
        fi
        ;;
    "search")
        # Search knowledge base
        query="$2"
        echo "🔍 Searching for: $query"
        grep -r -i "$query" "$BRAIN_DIR/knowledge/" "$BRAIN_DIR/progress/" | head -20
        ;;
    "status")
        # Show current status
        echo "🧠 Second Brain Status"
        echo "===================="
        echo "Knowledge entries: $(find $BRAIN_DIR/knowledge -name "*.md" | wc -l)"
        echo "Progress logs: $(find $BRAIN_DIR/progress -name "*.md" | wc -l)"
        echo "Projects: $(find $BRAIN_DIR/projects -maxdepth 1 -type d | wc -l)"
        echo "Last update: $(ls -t $BRAIN_DIR/progress/*.md 2>/dev/null | head -1 | xargs stat -f "%Sm" 2>/dev/null || echo 'No progress logged')"
        ;;
    "init")
        # Initialize brain for a project
        project="$2"
        if [[ -z "$project" ]]; then
            echo "❌ Please specify a project name"
            exit 1
        fi
        
        mkdir -p "$BRAIN_DIR/projects/$project"/{progress,notes,resources}
        
        cat > "$BRAIN_DIR/projects/$project/README.md" << EOL
# $project - Second Brain

**Created:** $DATE
**Status:** Active

## Overview
Brief description of the project.

## Goals
- [ ] Primary goal
- [ ] Secondary goal

## Progress Tracking
- Progress logs: \`./progress/\`
- Notes: \`./notes/\`
- Resources: \`./resources/\`

## Quick Commands
\`\`\`bash
brain task <task-id> "progress update"
brain insight "learning or insight" $project
brain review
\`\`\`

## Related Knowledge
- 

---
*Generated by Second Brain*
EOL
        
        echo "✅ Project brain initialized: $project"
        ;;
    *)
        echo "🧠 Second Brain CLI"
        echo "=================="
        echo ""
        echo "Commands:"
        echo "  brain log \"message\"              - Quick progress log"
        echo "  brain task <id> \"progress\"       - Log task progress"
        echo "  brain insight \"insight\" [project] - Capture insights"
        echo "  brain review                      - Generate daily review with AI"
        echo "  brain search \"query\"             - Search knowledge base"
        echo "  brain status                      - Show brain status"
        echo "  brain init <project>              - Initialize project brain"
        echo ""
        echo "Examples:"
        echo "  brain log \"Fixed authentication bug\""
        echo "  brain task 5.2 \"Completed subscription UI, needs testing\""
        echo "  brain insight \"Redux patterns work well for complex state\" tribefind"
        echo "  brain review"
        ;;
esac
EOF

chmod +x ~/.second-brain/scripts/brain

# Add to PATH if not already there
if ! grep -q "/.second-brain/scripts" ~/.zshrc; then
    echo 'export PATH="$HOME/.second-brain/scripts:$PATH"' >> ~/.zshrc
    echo "✅ Added brain CLI to PATH"
fi

echo ""
echo "🎉 Second Brain setup complete!"
echo ""
echo "Quick start:"
echo "  source ~/.zshrc  # Reload shell"
echo "  brain status     # Check status"
echo "  brain init tribefind  # Initialize for your project"
echo ""
echo "Integration ready with:"
echo "  ✅ Claude CLI (claude-code)"
echo "  ✅ Task Master (task-master)" 
echo "  ✅ Git integration"
echo "" 